[package]
name = "checksums"
description = "Tool for making/verifying checksums of directory trees"
documentation = "https://cdn.rawgit.com/nabijaczleweli/checksums/doc/checksums/index.html"
repository = "https://github.com/nabijaczleweli/checksums"
readme = "README.md"
keywords = ["checksums", "checksum", "directory", "verification", "hash", "md5", "crc", "sha", "sha2"]
license = "MIT"
# Remember to also update in appveyor.yml
version = "0.1.0"
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]
exclude = ["*.enc"]


[dependencies]
blake2-rfc = { git = "https://github.com/cesarb/blake2-rfc.git", rev = "0.2.17" }
tiny-keccak = "1.1"
tabwriter = "0.1"
shaman = "0.1"
blake = "1.0"
crc16 = "0.3"
clap = "2.10"
crc8 = "0.1"
crc = "1.3"
md5 = "0.2"
