[package]
name = "checksums"
description = "Tool for making/verifying checksums of directory trees"
documentation = "https://cdn.rawgit.com/nabijaczleweli/checksums/doc/checksums/index.html"
repository = "https://github.com/nabijaczleweli/checksums"
readme = "README.md"
keywords = ["checksums", "checksum", "directory", "verification", "hash"]
license = "MIT"
# Remember to also update in appveyor.yml
version = "0.2.1"
# Remember to also update in Synopsis.md
authors = ["nabijaczleweli <nabijaczleweli@gmail.com>"]
exclude = ["*.enc"]


[dependencies]
lazy_static = "0.2"
tiny-keccak = "1.1"
blake2-rfc = "0.2"
tabwriter = "0.1"
shaman = "0.1"
blake = "1.0"
crc16 = "0.3"
regex = "0.1"
clap = "2.10"
crc8 = "0.1"
crc = "1.3"
md5 = "0.2"


[[bin]]
name = "checksums"
doc = false
